---
- name: Preparar Servidor com Docker e Proxy Nginx
  hosts: local
  become: yes  # Executa como sudo
  
  tasks:
    - name: Atualizar cache do repositório

      apt:
        update_cache: yes

    - name: Instalar Docker e Nginx
      apt:
        name: 
          - docker.io
          - nginx
        state: latest
        update_cache: yes

    - name: Garantir que o Docker e Nginx estejam rodando
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - docker
        - nginx

    - name: Criar um container Docker (App de exemplo)
      community.docker.docker_container:
        name: minha-app
        image: nginxdemos/hello
        state: started
        ports:
          - "8080:80"

    - name: Configurar Nginx como Proxy Reverso
      copy:
        content: |
          server {
              listen 80;
              location / {
                  proxy_pass http://localhost:8080;
              }
          }
        dest: /etc/nginx/sites-available/default

    - name: Reiniciar Nginx para aplicar mudanças
      service:
        name: nginx
        state: restarted


    - name: Adicionar repositório oficial do Zabbix
      apt_repository:
        repo: deb https://repo.zabbix.com/zabbix/6.0/ubuntu focal main
        state: present
        update_cache: yes

    - name: Instalar Zabbix Agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configurar o Zabbix Agent (Server IP)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server=127.0.0.1,SEU_IP_ZABBIX_AQUI' # Coloque o IP do seu servidor Zabbix
        state: present

    - name: Garantir que o Zabbix Agent esteja rodando
      service:
        name: zabbix-agent
        state: started
        enabled: yes
