---
- name: Preparar Servidor com Docker e Proxy Nginx
  hosts: local
  become: yes  # Executa como sudo
  
  tasks:
    - name: Atualizar cache do repositório

      apt:
        update_cache: yes

    - name: Instalar Docker e Nginx
      apt:
        name: 
          - docker.io
          - nginx
        state: latest
        update_cache: yes

    - name: Garantir que o Docker e Nginx estejam rodando
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - docker
        - nginx

    - name: Criar um container Docker (App de exemplo)
      community.docker.docker_container:
        name: minha-app
        image: nginxdemos/hello
        state: started
        ports:
          - "8080:80"

    - name: Configurar Nginx como Proxy Reverso
      copy:
        content: |
          server {
              listen 80;
              location / {
                  proxy_pass http://localhost:8080;
              }
          }
        dest: /etc/nginx/sites-available/default

    - name: Reiniciar Nginx para aplicar mudanças
      service:
        name: nginx
        state: restarted


    # 1. CRIAR A REDE PRIMEIRO
    - name: Criar rede interna para os containers
      community.docker.docker_network:
        name: rede_infra
        state: present

    # 2. SUBIR O ZABBIX AGENT
    - name: Subir Zabbix Agent via Docker
      community.docker.docker_container:
        name: zabbix-agent
        image: zabbix/zabbix-agent:6.4-ubuntu-latest
        networks:
          - name: rede_infra
        ports:
          - "10050:10050"
        env:
          ZBX_HOSTNAME: "MeuServidorLinux"
          ZBX_SERVER_HOST: "127.0.0.1"
        restart_policy: always

    # 3. SUBIR O BANCO DE DADOS
    - name: Subir Banco de Dados MySQL
      community.docker.docker_container:
        name: db_projeto
        image: mysql:8.0
        networks:
          - name: rede_infra
        env:
          MYSQL_ROOT_PASSWORD: "senha_admin_vaga"
          MYSQL_DATABASE: "vaga_devops"
        restart_policy: always

    # 4. SUBIR O ADMINER (INTERFACE SQL)
    - name: Subir Interface SQL (Adminer)
      community.docker.docker_container:
        name: adminer_web
        image: adminer
        networks:
          - name: rede_infra
        ports:
          - "8081:8080" 

    volumes:
      - /home/{{ ansible_user_id }}/db_data:/var/lib/mysql
